import hero_bg from './images/hero bg.png';
import logo from './images/logo.svg';
import like from './images/like.svg';
import cart from './images/cart.svg';
import user from './images/user.svg';
import production_1 from './images/production-1.png';
import production_2 from './images/production-2.png';
import production_3 from './images/production-3.png';
import production_4 from './images/production-4.png';
import production_5 from './images/production-5.png';
import avatar from './images/avatar.png';
import choose_1 from './images/choose-1.png';
import img from './images/img.png';
import news_1 from './images/news-1.png';
import news_2 from './images/news-2.png';
import news_3 from './images/news-3.png';
import news_4 from './images/news-4.png';
import news_5 from './images/news-5.png';
import news_6 from './images/news-6.png';

export { hero_bg, logo, like, cart, user, production_1, production_2, production_3, production_4, production_5, avatar, choose_1, img, news_1, news_2, news_3, news_4, news_5, news_6 };